# Generated by Django 5.1.4 on 2026-01-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='plot_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='room_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
