# Generated by Django 5.1.4 on 2026-01-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_property_plot_number_property_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image_url',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
