# Generated by Django 5.1.4 on 2026-01-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_property_image_url_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/id_documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='proof_of_funds',
            field=models.FileField(blank=True, null=True, upload_to='applications/proof_of_funds/'),
        ),
    ]
