# Generated by Django 5.1.4 on 2026-01-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_application_document_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(blank=True, default='Starter', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='max_plots',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
