# Generated by Django 5.1.4 on 2026-01-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_property_layout_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='layout_image',
            field=models.FileField(blank=True, null=True, upload_to='properties/layouts/'),
        ),
    ]
