# Generated by Django 5.1.4 on 2026-01-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_property_financing_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Property Rentals', 'Property Rentals'), ('Commercial Rentals', 'Commercial Rentals'), ('Agricultural', 'Agricultural'), ('Land For Sale', 'Land For Sale'), ('Car Rentals', 'Car Rentals'), ('Other', 'Other')], default='Land For Sale', max_length=64),
        ),
    ]
