# Generated by Django 5.1.4 on 2026-01-27 00:00

import uuid

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='properties/images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.property')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
